#
#
# File: $Id: $
#
# Author: George V. Neville-Neil
#
# Makefile for updating Packet Debugger web pages.
FILES = *.html ../pdb.pdf html/

install::
	scp -r ${FILES} gnn@shell.sourceforge.net:/home/groups/p/pk/pktdbg/htdocs