#
#
# File: $Id: $
#
# Author: George V. Neville-Neil
#
# Makefile for updating Packet Debugger web pages.
FILES = *.html *.jpg *.py *.pdf

install::
	scp ${FILES} gnn@shell.sourceforge.net:/home/groups/p/pk/pktdbg/htdocs